version: "3.2"

services:
  dev:
    container_name: appchain-barnacle
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/appchain-barnacle
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/appchain-barnacle/.cargo
    volumes:
      - .:/var/www/appchain-barnacle
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/appchain-barnacle --dev --ws-external"
