blank_issues_enabled: false
contact_links:
  - name: Support & Troubleshooting with the Substrate Stack Exchange Community
    url: https://substrate.stackexchange.com
    about: |
      For general problems with Substrate or related technologies, please search here first
      for solutions, by keyword and tags. If you discover no solution, please then ask and questions in our community! We highly encourage everyone also share their understanding by answering questions for others.
  - name: Feature Requests and PRs to be submitted upstream
    url: https://github.com/paritytech/substrate/tree/master/bin/node-template
    about: |
      This template is generated on tagged releases upstream, it is not independently updated and maintained.
      Please direct all suggestions for improvements and PRs upstream.
